# Heavily based on workflow in https://github.com/zesterer/chumsky/

name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

permissions: read-all

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run cargo check (all features)
        run: cargo check --benches --examples --tests --verbose --all-features
      - name: Run cargo clippy
        run: cargo clippy --benches --examples --tests --verbose --all-features -- -D warnings
      - name: Run cargo fmt
        run: cargo fmt --verbose --check
      - name: Run cargo doc
        run: cargo doc --all-features --verbose
        env:
          RUSTDOCFLAGS: --cfg docsrs
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install latest stable
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Run cargo test
        run: cargo test --verbose --all-features
        env:
          RUSTDOCFLAGS: --cfg docsrs
  msrv:
    name: MSRV
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install MSRV
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: "1.65"
          components: rustfmt, clippy
      - name: Check MSRV compatibility
        run: cargo check --verbose --all-features
  semver:
    name: SemVer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check semver compatibility
        uses: obi1kenobi/cargo-semver-checks-action@v2
        with:
          rust-toolchain: stable